name: RenderApi

on:
  push:
    branches: [master]
  workflow_dispatch: ~


jobs:
  Linux:
    name: Test and Render API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: master
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2023.5.8
          compression: bzip # no, it is actually xz but tar will figure that out hopefully...
      - name: Run test suites
        run: inso run test spc_8ea7cf -e env_env_9a21f4d181d64765d33c7bbe158a0e24fc2976d0 --verbose
      - name: Generate yaml
        run: inso export spec spc_8ea7cf > openapi.yaml
      - name: JSON from YAML
        run: cat ./openapi.yaml | sed "s/\\\\\//\//g" | yq -o json > ./openapi.json
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'rerender openapi.yaml'
          add: "['*.yaml', '*.json']"
          push: true